version: "3"

services:
    SQLBot-frontend:
        shm_size: 4gb
        image: hyukkyukang/sqlbot:latest
        container_name: SQLBot-frontend
        stdin_open: true
        tty: true
        network_mode: "host"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./:/root/sqlbot

    SQLBot-backend:
        shm_size: 4gb
        image: hyukkyukang/nl2qgm:latest
        container_name: SQLBot-backend
        stdin_open: true
        tty: true
        network_mode: "host"
        environment:
            - TZ=Asia/Seoul
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./third_party/nl2qgm:/root/nl2qgm
            - redis_data:/root/sqlbot/data/redis/
            - /mnt:/mnt
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

    SQLBot-redis:
        image: redis:latest
        container_name: SQLBot-redis
        volumes:
            - redis_data:/data
        ports:
            - target: 6379
              published: 6379
        networks:
            - redis

    SQLBot-postgres:
        image: postgres:16.6
        container_name: SQLBot-postgres
        stdin_open: true
        tty: true
        shm_size: 8gb
        ports:
            - "5434:5432" # host:container
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./data/postgresql:/var/lib/postgresql/data

volumes:
    redis_data:
        driver: local

networks:
    redis:
        driver: bridge
